@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

//As a QueryString parameter
GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/?X-ApiKey=hgghjhncsjdvacadc45ojvacaofijva=7894FJODJFfvjafjadfkjflkvjaiodfjfpaosjf65461
Accept: application/json

###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/?X-ApiKey=BV60HsJjG2a229zZuJ9Foya2xJpQKAR04LJVcrUO4vKYhSLhJ0p5ItcfdAfhGxcvgyJPKQ3ucyeeoPa2i2LCyQ==
Accept: application/json

###

//Via a custom header
GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
X-ApiKey: hgghjhncsjdvacadc45ojvacaofijva=7894FJODJFfvjafjadfkjflkvjaiodfjfpaosjf65461
Accept: application/json

###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
X-ApiKey: BV60HsJjG2a229zZuJ9Foya2xJpQKAR04LJVcrUO4vKYhSLhJ0p5ItcfdAfhGxcvgyJPKQ3ucyeeoPa2i2LCyQ==
Accept: application/json

###