@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json
  
###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkEiLCJzdWIiOiJBIiwianRpIjoiY2NmMTkwYWUiLCJhZ2UiOiIyNSIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImF1ZCI6IndlYXRoZXJmb3JlY2FzdGFwaSIsIm5iZiI6MTc2OTgzNTk1NSwiZXhwIjoxNzc3NTI1NTU1LCJpYXQiOjE3Njk4MzU5NTUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.hDpuhXO8amRr3Ln6xvFFq_PBE1hvxFjeZIpJnaRpzBs
Accept: application/json 

###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/abc113
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkEiLCJzdWIiOiJBIiwianRpIjoiY2NmMTkwYWUiLCJhZ2UiOiIyNSIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImF1ZCI6IndlYXRoZXJmb3JlY2FzdGFwaSIsIm5iZiI6MTc2OTgzNTk1NSwiZXhwIjoxNzc3NTI1NTU1LCJpYXQiOjE3Njk4MzU5NTUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.hDpuhXO8amRr3Ln6xvFFq_PBE1hvxFjeZIpJnaRpzBs
Accept: application/json 

###