@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json
  
###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkEiLCJzdWIiOiJBIiwianRpIjoiYWZlOGY3MGIiLCJhZ2UiOiIyMyIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImF1ZCI6IndlYXRoZXJmb3JlY2FzdGFwaSIsIm5iZiI6MTc2OTc5NjEyMiwiZXhwIjoxNzc3NTcyMTIyLCJpYXQiOjE3Njk3OTYxMjMsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.GvlQIDbUU5hTaaVV49UQ_5Yzcr24ZrV5zkse2tvAsac
Accept: application/json 